import medico from './medico 1.png'
import HeroImage from './HeroImage.png'

import BoneProblem from './BoneProblem.webp'
import BreathingProblem from './BreathingProblem.webp'
import EyeProblem from './EyeProblem.webp'
import HeartProblem from './HeartProblem.webp'
import KidneyProblem from './KidneyProblem.webp'
import LiverProblem from './LiverProblem.webp'
import SkinProblem from './SkinProblem.webp'
import StomachProblem from './StomachProblem.webp'
import Diabeties from './Diabeties.webp'

import medstore1 from './medstore1.jpg'
import medstore2 from './medstore2.jpg'
import medstore3 from './medstore3.jpg'
import medstore4 from './medstore4.jpg'
import medstore5 from './medstore5.jpg'

import star from './star.png'
import WebImage from './WebImage.webp'
import Doctor from './Doctor.jpg'
import  cross_icon from './cross_icon.png'
import remove_icon_red from './remove_icon_red.png'
import add_icon_green from './add_icon_green.png'

import BabyCare from './BabyCare.webp'
import MonsoonEssentials from './MonsoonEssentials.webp'
import PersonalCare from './PersonalCare.webp'
import Nutrition from './Nutrition.webp'
import SkinCare from './SkinCare.webp'
import WomenCare from './WomenCare.webp'
import ProtienSupp from './ProtienSupp.webp'
import Multivitamins from './Multivitamins.webp'
import Glucometer from './Glucometer.webp'
import HealthDevices from './HealthDevices.webp'
import Ayurveda from './Ayurveda.webp'
import Food from './Food.webp'

import AIMIL from './BrandImages/AIMIL.webp'
import AVP from './BrandImages/AVP.webp'
import Dabur from './BrandImages/Dabur.webp'
import Dettol from './BrandImages/Dettol.webp'
import Durex from './BrandImages/Durex.webp'
import Himalaya from './BrandImages/Himalaya.webp'
import Mamaearth from './BrandImages/MamaEarth.webp'
import Morpen from './BrandImages/Morpen.webp'
import Nivea from './BrandImages/Nivea.webp'
import Protinex from './BrandImages/Protinex.webp'

import Boost from './OfferProductImages/Boost.jpg'
import Complan from './OfferProductImages/Complan.jpg'
import Everyuth from './OfferProductImages/Everyuth.jpg'
import Horlics from './OfferProductImages/Horlics.jpg'
import Huggies from './OfferProductImages/Huggies.jpg'
import HuggiesPants from './OfferProductImages/HuggiesPants.jpg'
import Iodex from './OfferProductImages/Iodex.jpg'
import LakmeFW from './OfferProductImages/LakmeFW.jpg'
import LittlesWipes from './OfferProductImages/LittlesWipes.jpg'
import NekoWipes from './OfferProductImages/NekoWipes.jpg'
import NiveaSpray from './OfferProductImages/NiveaSpray.jpg'
import PampersPants from './OfferProductImages/PampersPants.jpg'
import Vaseline from './OfferProductImages/Vaseline.jpg'

export const assets={
    medico,
    HeroImage,
    star,
    WebImage,
    Doctor,
    cross_icon,
    add_icon_green,
    remove_icon_red,

// Brand Images
    medstore1,
    medstore2,
    medstore3,
    medstore4,
    medstore5,
// Brand Images
    AIMIL,
    AVP,
    Dabur,
    Dettol,
    Durex,
    Himalaya,
    Mamaearth,
    Morpen,
    Nivea,
    Protinex
}

export const HealthProblemsList=[
    {
        HealthProblemName:"Body Pains",
        HealthProblemImage: BoneProblem
    },
    {
        HealthProblemName:"Joint Pains",
        HealthProblemImage: BreathingProblem
    },
    {
        HealthProblemName:"Fever",
        HealthProblemImage: HeartProblem
    },
    {
        HealthProblemName:"Cold",
        HealthProblemImage: BreathingProblem
    },
    {
        HealthProblemName:"Stomach Pain",
        HealthProblemImage: StomachProblem
    },
    {
        HealthProblemName:"Skin Infection",
        HealthProblemImage: SkinProblem
    },
    {
        HealthProblemName:"Diabeties",
        HealthProblemImage: Diabeties
    },
    {
        HealthProblemName:"Blood Pressure",
        HealthProblemImage: LiverProblem
    },
    {
        HealthProblemName:"First Aid",
        HealthProblemImage: BoneProblem
    },
    {
        HealthProblemName:"Diabeties",
        HealthProblemImage: Diabeties
    },
    {
        HealthProblemName:"Blood Pressure",
        HealthProblemImage: LiverProblem
    },
    {
        HealthProblemName:"First Aid",
        HealthProblemImage: BoneProblem
    },
    {
        HealthProblemName:"Diabeties",
        HealthProblemImage: Diabeties
    },
    {
        HealthProblemName:"Blood Pressure",
        HealthProblemImage: LiverProblem
    },
    {
        HealthProblemName:"First Aid",
        HealthProblemImage: BoneProblem
    }
]

export const Category=[
    {
        CategoryImage:BabyCare,
        CategoryName:"Baby Care"
    },
    {
        CategoryImage:Ayurveda,
        CategoryName:"Ayurveda"
    },
    {
        CategoryImage: MonsoonEssentials,
        CategoryName:"Monsoon Essentials"
    },
    {
        CategoryImage:Nutrition,
        CategoryName:"Nutrition"
    },
    {
        CategoryImage:SkinCare,
        CategoryName:"Skin Care"
    },
    {
        CategoryImage:WomenCare,
        CategoryName:"Women Care"
    },
    {
        CategoryImage:ProtienSupp,
        CategoryName:"ProtienSupp"
    },
    {
        CategoryImage:Multivitamins,
        CategoryName:"Multivitamins"
    },
    {
        CategoryImage:PersonalCare,
        CategoryName:"Personal Care"
    },
    {
        CategoryImage:Glucometer,
        CategoryName:"Glucometer"
    },
    {
        CategoryImage:Food,
        CategoryName:"Food"
    },
    {
        CategoryImage:HealthDevices,
        CategoryName:"HealthDevices"
    }
]

export const OfferProducts=[
    {
        ProductImage:Boost,
        ProductName:"BOOST 1KG CONTAINER ( 500GM X 2 ) REFILL PACK",
        ProductSellingPrice:"505.00",
        ProductOriginalPrice:"600.00"
    },
    {
        ProductImage:Complan,
        ProductName:"COMPLAN CHOCOLATE REFILL 1KG",
        ProductSellingPrice:"600.00",
        ProductOriginalPrice:"629.00"
    },
    {
        ProductImage:Everyuth,
        ProductName:"EVERYUTH NATURALS BODY LOTION NOURISHING COCOA 200ML",
        ProductSellingPrice:"250.00",
        ProductOriginalPrice:"270.00"
    },
    {
        ProductImage:Horlics,
        ProductName:"Horlicks Promo Pack 500Gm X 2",
        ProductSellingPrice:"520.00",
        ProductOriginalPrice:"600.00"
    },
    {
        ProductImage:Huggies,
        ProductName:"HUGGIES WONDERPANTS DIAPER L64",
        ProductSellingPrice:"1399.00",
        ProductOriginalPrice:"1469.00"
    },
    {
        ProductImage:HuggiesPants,
        ProductName:"HUGGIES WONDER PANTS MEGA JUMBO PACK M 120S",
        ProductSellingPrice:"1649.00",
        ProductOriginalPrice:"1700.00"
    },
    {
        ProductImage:Iodex,
        ProductName:"IODEX RAPID ACTION SPRAY 60GM",
        ProductSellingPrice:"220.00",
        ProductOriginalPrice:"240.00"
    },
    {
        ProductImage:LakmeFW,
        ProductName:"LAKME BLUSH AND GLOW STRAWBERRY GEL FACE WASH 100GM",
        ProductSellingPrice:"182.00",
        ProductOriginalPrice:"190.00"
    },
    {
        ProductImage:LittlesWipes,
        ProductName:"LITTLES BABY WIPES 80S",
        ProductSellingPrice:"95.00",
        ProductOriginalPrice:"190.00"
    },
    {
        ProductImage:NekoWipes,
        ProductName:"NEKO GERM PROTECTION LARGE WIPES 80'S",
        ProductSellingPrice:"174.00",
        ProductOriginalPrice:"199.00"
    },
    {
        ProductImage:NiveaSpray,
        ProductName:"NIVEA MEN FRESH ACTIVE ORIGINAL DEODRANT, 150 ML",
        ProductSellingPrice:"228.00",
        ProductOriginalPrice:"250.00"
    },
    {
        ProductImage:PampersPants,
        ProductName:"PAMPERS PANTS NEW BABY 86S",
        ProductSellingPrice:"1039.00",
        ProductOriginalPrice:"1299.00"
    },
    {
        ProductImage:Vaseline,
        ProductName:"VASELINE DAILY BRIGHTENING 400ML LOTION",
        ProductSellingPrice:"271.88",
        ProductOriginalPrice:"435.00"
    }
]
export const CartItems=[
    {
        ProductImage:Boost,
        ProductName:"BOOST 1KG CONTAINER ( 500GM X 2 ) REFILL PACK",
        ProductSellingPrice:"505.00",
        ProductOriginalPrice:"600.00"
    },
    {
        ProductImage:Complan,
        ProductName:"COMPLAN CHOCOLATE REFILL 1KG",
        ProductSellingPrice:"600.00",
        ProductOriginalPrice:"629.00"
    },
    {
        ProductImage:Everyuth,
        ProductName:"EVERYUTH NATURALS BODY LOTION NOURISHING COCOA 200ML",
        ProductSellingPrice:"250.00",
        ProductOriginalPrice:"270.00"
    },
    {
        ProductImage:Horlics,
        ProductName:"Horlicks Promo Pack 500Gm X 2",
        ProductSellingPrice:"520.00",
        ProductOriginalPrice:"600.00"
    },
    {
        ProductImage:Huggies,
        ProductName:"HUGGIES WONDERPANTS DIAPER L64",
        ProductSellingPrice:"1399.00",
        ProductOriginalPrice:"1469.00"
    },
    {
        ProductImage:HuggiesPants,
        ProductName:"HUGGIES WONDER PANTS MEGA JUMBO PACK M 120S",
        ProductSellingPrice:"1649.00",
        ProductOriginalPrice:"1700.00"
    },
    {
        ProductImage:Iodex,
        ProductName:"IODEX RAPID ACTION SPRAY 60GM",
        ProductSellingPrice:"220.00",
        ProductOriginalPrice:"240.00"
    },
    {
        ProductImage:LakmeFW,
        ProductName:"LAKME BLUSH AND GLOW STRAWBERRY GEL FACE WASH 100GM",
        ProductSellingPrice:"182.00",
        ProductOriginalPrice:"190.00"
    },
    {
        ProductImage:LittlesWipes,
        ProductName:"LITTLES BABY WIPES 80S",
        ProductSellingPrice:"95.00",
        ProductOriginalPrice:"190.00"
    },
    {
        ProductImage:NekoWipes,
        ProductName:"NEKO GERM PROTECTION LARGE WIPES 80'S",
        ProductSellingPrice:"174.00",
        ProductOriginalPrice:"199.00"
    },
    {
        ProductImage:NiveaSpray,
        ProductName:"NIVEA MEN FRESH ACTIVE ORIGINAL DEODRANT, 150 ML",
        ProductSellingPrice:"228.00",
        ProductOriginalPrice:"250.00"
    },
    {
        ProductImage:PampersPants,
        ProductName:"PAMPERS PANTS NEW BABY 86S",
        ProductSellingPrice:"1039.00",
        ProductOriginalPrice:"1299.00"
    },
    {
        ProductImage:Vaseline,
        ProductName:"VASELINE DAILY BRIGHTENING 400ML LOTION",
        ProductSellingPrice:"271.88",
        ProductOriginalPrice:"435.00"
    }
]

export const MedicineList=[{Medicine:"Amitriptyline Hydrochloride"},
    {Medicine:"DG Health Cold and Flu Relief"},
    {Medicine:"WHITE LAVENDER AND MINT ANTIBACTERIAL MOISTURIZING HAND SP"},
    {Medicine:"hand"},
    {Medicine:"INDOMETHACIN"},
    {Medicine:"Opcon-A"},
    {Medicine:"Diathesis"},
    {Medicine:"allergy"},
    {Medicine:"Childrens Acetaminophen"},
    {Medicine:"ONDANSETRON HYDROCHLORIDE"},
    {Medicine:"Metoclopramide"},
    {Medicine:"ETHYL ALCOHOL"},
    {Medicine:"lice"},
    {Medicine:"HOUSE DUST"},
    {Medicine:"Amlodipine Besylate and Benazepril HCL"},
    {Medicine:"Atenolol"},
    {Medicine:"Tobramycin Sulfate"},
    {Medicine:"Rohto"},
    {Medicine:"Topcare Nite Time Cold and Flu"},
    {Medicine:"Carbidopa and Levodopa"},
    {Medicine:"LOreal Paris Revitalift Miracle Blur Broad Spectrum SPF 30 Sunscreen"},
    {Medicine:"Cedar X Pet Formula"},
    {Medicine:"Multi-Symptom Nighttime Cold"},
    {Medicine:"Topical Anesthetic"},
    {Medicine:"IBU"},
    {Medicine:"ATORVASTATIN CALCIUM"},
    {Medicine:"Kaletra"},
    {Medicine:"Naproxen Sodium"},
    {Medicine:"Hydrochlorothiazide"},
    {Medicine:"Zosyn"},
    {Medicine:"CYPROHEPTADINE HYDROCHLORIDE"},
    {Medicine:"Alcohol Prep Pad with Benzocaine"},
    {Medicine:"Pure Finish Mineral Powder Foundation SPF 20"},
    {Medicine:"ClearAc"},
    {Medicine:"Hydrocodone Bitartrate And Acetaminophen"},
    {Medicine:"Hand Sanitizer"},
    {Medicine:"Strattera"},
    {Medicine:"Terazosin Hydrochloride"},
    {Medicine:"Venlafaxine Hydrochloride"},
    {Medicine:"Lithium Carbonate"},
    {Medicine:"DEPRESSION COMPOSITION"},
    {Medicine:"Hand Sanitizer with Moisturizers"},
    {Medicine:"Tacrolimus"},
    {Medicine:"Liver Drainage"},
    {Medicine:"Ceftriaxone Sodium"},
    {Medicine:"Clonazepam"},
    {Medicine:"PRIMAXIN"},
    {Medicine:"Petroleum"},
    {Medicine:"cephalexin"},
    {Medicine:"Solar Protection Formula SPF 58"},
    {Medicine:"Neutrogena"},
    {Medicine:"Hawaiian Tropic"},
    {Medicine:"Citrus Burst Antibacterial Cleansing Hand Wash"},
    {Medicine:"Nitroglycerin"},
    {Medicine:"Dehydrated Alcohol"},
    {Medicine:"XtraCare with cooling action Oatmeal Skin Relief Calmin"},
    {Medicine:"Fluocinolone Acetonide"},
    {Medicine:"Head and Shoulders"},
    {Medicine:"AHAVA ACTIVE DEADSEA MINERALS"},
    {Medicine:"Hydrocortisone Acetate"},
    {Medicine:"SOLIE EMULSION"},
    {Medicine:"Neutrogena MoistureShine SPF20"},
    {Medicine:"NEXIUM"},
    {Medicine:"Flawless Finish Bare Perfection Makeup SPF 8 Mocha"},
    {Medicine:"Nortriptyline Hydrochloride"},
    {Medicine:"Nortriptyline Hydrochloride"},
    {Medicine:"Lithostat"},
    {Medicine:"Honeysuckle Ginger Hand Sanitizer"},
    {Medicine:"Oil-Free Daily Hydration SPF 15"},
    {Medicine:"Cefotetan and Dextrose"},
    {Medicine:"Demeclocycline Hydrochloride"},
    {Medicine:"OLANZAPINE"},
    {Medicine:"Mycophenolic Acid"},
    {Medicine:"Oxacillin"},
    {Medicine:"Dextroamphetamine Sulfate"},
    {Medicine:"Sildenafil"},
    {Medicine:"CD DiorSkin Forever Flawless Perfection Fusion Wear Makeup SPF 25 - 020"},
    {Medicine:"Foamy Med-I-San"},
    {Medicine:"Good Sense Nicotine"},
    {Medicine:"Epinephrine"},
    {Medicine:"Isradipine"},
    {Medicine:"Vibativ"},
    {Medicine:"Cephalexin"},
    {Medicine:"Metformin Hydrochloride"},
    {Medicine:"Peaches and Cream Antibacterial Foaming Hand Wash"},
    {Medicine:"NITROGEN"},
    {Medicine:"NITROUS OXIDE"},
    {Medicine:"ESIKA HD COLOR HIGH DEFINITION COLOR SPF 20"},
    {Medicine:"Pramipexole Dihydrochloride"},
    {Medicine:"K-Tab"},
    {Medicine:"INSTANT HAND SANITIZER"},
    {Medicine:"Mucinex Fast-Max"},
    {Medicine:"Amlodipine Besylate"},
    {Medicine:"pain and fever"},
    {Medicine:"Isopropyl Alcohol"},
    {Medicine:"Suave"},
    {Medicine:"Latuda"},
    {Medicine:"DERMA GRAN"},
    {Medicine:"Rimmel London"},
    {Medicine:"Alprazolam"},
    {Medicine:"Hydrochlorothiazide"},
    {Medicine:"B-Nexa"},
    {Medicine:"PEAR"},
    {Medicine:"Sunkissed Honeydew Hand Sanitizer"},
    {Medicine:"Severe Cold and Flu"},
    {Medicine:"Cheratussin AC"},
    {Medicine:"Bayberry"},
    {Medicine:"REOROM"},
    {Medicine:"Hydrocodone Bitartrate and Acetaminophen"},
    {Medicine:"Strattera"},
    {Medicine:"Fruit Punch Scented Hand Sanitizer"},
    {Medicine:"Lidocaine Hydrochloride"},
    {Medicine:"Cold and Flu BP"},
    {Medicine:"Montelukast Sodium"},
    {Medicine:"lisinopril"},
    {Medicine:"Chaetomium"},
    {Medicine:"PROAIR"},
    {Medicine:"SEROQUEL"},
    {Medicine:"Lisinopril and Hydrochlorothiazide"},
    {Medicine:"MIDAZOLAM"},
    {Medicine:"naproxen sodium"},
    {Medicine:"laura mercier Tinted Moisturizer Creme Compact Broad Spectrum SPF 20 Sunscreen TAN"},
    {Medicine:"BELLA SCHNEIDER BEAUTY Glow And Go Tinted Moisturizing Sunscreen Broad Spectrum SPF 30"},
    {Medicine:"Fosinopril Sodium and Hydrochlorothiazide"},
    {Medicine:"Pentazocine and naloxone"},
    {Medicine:"Coldaid"},
    {Medicine:"Carbamazepine"},
    {Medicine:"PredniSONE"},
    {Medicine:"Instant Hand Sanitizer Sugar Plum"},
    {Medicine:"Nitroglycerin Transdermal Delivery System"},
    {Medicine:"Escitalopram oxalate"},
    {Medicine:"Potassium Chloride in Dextrose and Sodium Chloride"},
    {Medicine:"Octreotide Acetate"},
    {Medicine:"Perindopril Erbumine"},
    {Medicine:"Gas Relief"},
    {Medicine:"HALIBUT"},
    {Medicine:"United Lab Antibac"},
    {Medicine:"Rivastigmine Tartrate"},
    {Medicine:"enMotion"},
    {Medicine:"Childrens Pain Relief"},
    {Medicine:"Dexamethasone"},
    {Medicine:"Levothyroxine sodium"},
    {Medicine:"Risperidone"},
    {Medicine:"GEODON"},
    {Medicine:"Soft Care Foaming Antibacterial Hand"},
    {Medicine:"Ketek"},
    {Medicine:"Milk of Magnesia Original"},
    {Medicine:"Warfarin Sodium"},
    {Medicine:"Mandarin Orange Antibacterial Foaming Hand Wash"},
    {Medicine:"Extra action Cough"},
    {Medicine:"Carvedilol"},
    {Medicine:"Vitis Stibium"},
    {Medicine:"Solmeet"},
    {Medicine:"Denpo"},
    {Medicine:"Ibuprofen"},
    {Medicine:"Heartery"},
    {Medicine:"Lidocaine Hydrochloride"},
    {Medicine:"Glimepiride"},
    {Medicine:"Fentanyl Citrate"},
    {Medicine:"XtraCare Dry Fresh Invisible Solid"},
    {Medicine:"Diltiazem Hydrochloride"},
    {Medicine:"Mischievous Orange Antibacterial Foaming Hand Wash"},
    {Medicine:"Hypothalmupar"},
    {Medicine:"Corn Removers"},
    {Medicine:"Ultra-TechneKow"},
    {Medicine:"TROSPIUM CHLORIDE"},
    {Medicine:"Arthritis"},
    {Medicine:"Helleborus e pl. tota 4"},
    {Medicine:"Pollens - Trees, Palm, Queen Cocos plumosa"},
    {Medicine:"isosorbide mononitrate"},
    {Medicine:"Gas Relief"},
    {Medicine:"Pramipexole Dihydrochloride"},
    {Medicine:"Firebush/Burning Bush"},
    {Medicine:"Cyclo/Mag 10mg/200mg"},
    {Medicine:"ALMOND"},
    {Medicine:"Diarrhea Relief"},
    {Medicine:"MALARONE"},
    {Medicine:"MDSOLARSCIENCES"},
    {Medicine:"Bumetanide"},
    {Medicine:"Standardized Mite, Dermatophagoides pteronyssinus, Intradermal, 30 AU per mL"},
    {Medicine:"SoftSoap Antibacterial with moisturizers Fresh Citrus"},
    {Medicine:"Escitalopram"},
    {Medicine:"Truth Revealed super creme SPF 15"},
    {Medicine:"Medi-First"},
    {Medicine:"Nighttime Sleep Aid"},
    {Medicine:"Atovaquone and Proguanil Hydrochloride"},
    {Medicine:"Inderal"},
    {Medicine:"Sandostatin LAR Depot"},
    {Medicine:"STOOL SOFTENER DOCUSATE SODIUM 50 MG"},
    {Medicine:"Belladonna ex herba 30"},
    {Medicine:"Naltrexone Hydrochloride"},
    {Medicine:"Prednisone"},
    {Medicine:"FNG"},
    {Medicine:"Cetirizine Hydrochloride"},
    {Medicine:"Antibacterial"},
    {Medicine:"careone milk of magnesia"},
    {Medicine:"Hydroxyzine Hydrochloride"},
    {Medicine:"Tahitian Noni Lip Balm Berry"},
    {Medicine:"OXYCODONE HYDROCHLORIDE"},
    {Medicine:"Antibacterial Hand Towelettes"},
    {Medicine:"Prozac"},
    {Medicine:"Rimmel London"},
    {Medicine:"Nabumetone"},
    {Medicine:"Bamboo Sap Patch"},
    {Medicine:"Leader Kids"},
    {Medicine:"Purmist"},
    {Medicine:"Cortifoam"},
    {Medicine:"TIMOLOL MALEATE"},
    {Medicine:"Calcium Acetate"},
    {Medicine:"Dobutamine Hydrochloride"},
    {Medicine:"Preferred Plus Ibuprofen"},
    {Medicine:"Propranolol Hydrochloride"},
    {Medicine:"SUGAR FREE LEMON MINT HERB THROAT DROPS"},
    {Medicine:"Biobron"},
    {Medicine:"Dior Snow Light Veil 010 Ivory SPF 20"},
    {Medicine:"Cefprozil"},
    {Medicine:"Non-Aerosol Antimicrobial Foam Hand Rub"},
    {Medicine:"Glyburide"},
    {Medicine:"Citalopram Hydrobromide"},
    {Medicine:"Ipratropium Bromide"},
    {Medicine:"Mirtazapine"},
    {Medicine:"Fluocinonide"},
    {Medicine:"Ludent"},
    {Medicine:"Alcortin"},
    {Medicine:"Prenate AM"},
    {Medicine:"Lyrica"},
    {Medicine:"Oxycodone Hydrochloride"},
    {Medicine:"Valproic Acid"},
    {Medicine:"Amoxicillin"},
    {Medicine:"Climate Adaptation Cold and Dry"},
    {Medicine:"Keppra"},
    {Medicine:"Integrilin"},
    {Medicine:"Antibacterial Hand"},
    {Medicine:"Carisoprodol"},
    {Medicine:"Sucralfate"},
    {Medicine:"healthy accents tussin chest congestion"},
    {Medicine:"Eszopiclone"},
    {Medicine:"Umecta"},
    {Medicine:"good neighbor pharmacy pain relief"},
    {Medicine:"ProCure Hand Sanitizing"},
    {Medicine:"Gemcitabine"},
    {Medicine:"ROUGH MARSHELDER POLLEN"},
    {Medicine:"cold and flu relief"},
    {Medicine:"OI LIN DEEP MOISTURE SUNSCREEN SPF 25"},
    {Medicine:"topiramate"},
    {Medicine:"Minocycline hydrochloride"},
    {Medicine:"GABAPENTIN"},
    {Medicine:"Oxaprozin"},
    {Medicine:"Bayberry"},
    {Medicine:"Sucrets"},
    {Medicine:"Etodolac"},
    {Medicine:"Isopto Atropine"},
    {Medicine:"PROVENCE TWO WAY PACT"},
    {Medicine:"PCXX ONE MINTE GEL MARSHMALLOW FLOAT"},
    {Medicine:"Warm Honey Always Color Stay-on Makeup Broad Spectrum SPF 15"},
    {Medicine:"Quetiapine Fumarate"},
    {Medicine:"AMBROSIA BIDENTATA POLLEN"},
    {Medicine:"TMC-A Hair Tonic"},
    {Medicine:"Clindamycin Hydrochloride"},
    {Medicine:"ESIKA"},
    {Medicine:"Alcohol Prep"},
    {Medicine:"PEPSOM SPORTS WINTERGREEN"},
    {Medicine:"flu and severe cold and cough"},
    {Medicine:"Simvastatin"},
    {Medicine:"MATTE MOISTURE TINT SUNSCREEN BROAD SPECTRUM SPF 15"},
    {Medicine:"GaviLyte - N"},
    {Medicine:"ALNUS INCANA SSP RUGOSA POLLEN"},
    {Medicine:"ENTOCORT"},
    {Medicine:"Lobelia Inflata"},
    {Medicine:"GUAIFENESIN"},
    {Medicine:"WellPatch Capsaicin Pain Relief"},
    {Medicine:"Clozapine"},
    {Medicine:"promethazine hydrochloride and codeine phosphate"},
    {Medicine:"HCG Plus"},
    {Medicine:"NITROGEN"},
    {Medicine:"Imipramine Hydrochloride"},
    {Medicine:"Neutrogena Oil Free Acne Wash"},
    {Medicine:"Proparacaine Hydrochloride"},
    {Medicine:"HYDRA LIFE PRO-YOUTH SKIN TINT 1"},
    {Medicine:"Venlafaxine Hydrochloride"},
    {Medicine:"Sulfamethoxazole and Trimethoprim"},
    {Medicine:"Triple Antibiotic"},
    {Medicine:"Ampicillin and Sulbactam"},
    {Medicine:"Therapeutic T Plus"},
    {Medicine:"Furosemide"},
    {Medicine:"Degree Nature Effects Orange Flower and Cranberry"},
    {Medicine:"Haloperidol"},
    {Medicine:"WATERMELON FROST SORE THROAT"},
    {Medicine:"sunmark ibuprofen"},
    {Medicine:"Colloidal Silver"},
    {Medicine:"Ciprofloxacin"},
    {Medicine:"Mucus Relief D"},
    {Medicine:"CELL BOOSTING BB"},
    {Medicine:"Oxygen"},
    {Medicine:"ORAL ASSIST"},
    {Medicine:"Moist SURE"},
    {Medicine:"Vanilla Sugar Antibacterial Hand Sanitizer"},
    {Medicine:"Treatment Set TS332256"},
    {Medicine:"Micro-K 10 Extencaps"},
    {Medicine:"Mirapex"},
    {Medicine:"Lip Protector Sunscreen SPF15"},
    {Medicine:"Monilia Mixture"},
    {Medicine:"Chlorhexidine Gluconate"},
    {Medicine:"Lysol"},
    {Medicine:"Tizanidine"},
    {Medicine:"Butalbital, Acetaminophen and Caffeine with Codeine Phosphate"},
    {Medicine:"Isopropyl Alcohol"},
    {Medicine:"Pedesil"},
    {Medicine:"Mag-AL Liquid"},
    {Medicine:"Pseudoephedrine Hydrochloride"},
    {Medicine:"Nicotine polacrilex"},
    {Medicine:"Hydroxyzine Hydrochloride"},
    {Medicine:"Hydralazine Hydrochloride"},
    {Medicine:"Delsym"},
    {Medicine:"Lil Drug Store Cold Relief"},
    {Medicine:"Nystatin"},
    {Medicine:"DocQLace"},
    {Medicine:"donepezil hydrochloride"},
    {Medicine:"JUNIPERUS CALIFORNICA POLLEN"},
    {Medicine:"Eve Lom Brilliant Cover Concealer Broad Spectrum SPF 15 Sunscreen"},
    {Medicine:"Prednisolone Sodium Phosphate"},
    {Medicine:"Leader Antacid"},
    {Medicine:"NEXIUM"},
    {Medicine:"Apidra"},
    {Medicine:"Physician EZ Use Joint Tunnel and Trigger Kit"},
    {Medicine:"Care One Maximum Strength First Aid Antibiotic"},
    {Medicine:"NITRO-DUR"},
    {Medicine:"FENTORA"},
    {Medicine:"TRISPEC DMX Pediatric Drops Cough Suppressant Expectorant CHERRY RASPBERRY Flavor"},
    {Medicine:"hydropel sports"},
    {Medicine:"Betamethasone Dipropionate"},
    {Medicine:"ARTEMIS Alcohol-Free Antiseptic Foam Hand Sanitizer"},
    {Medicine:"Nalbuphine Hydrochloride"},
    {Medicine:"SANCTURA"},
    {Medicine:"Valacyclovir Hydrochloride"},
    {Medicine:"Hydrochlorothiazide"},
    {Medicine:"Neomycin and Polymyxin B Sulfates, Bacitracin Zinc and Hydrocortisone"},
    {Medicine:"LBEL COULEUR LUXE AMPLIFIER XP"},
    {Medicine:"Nighttime Sinus Relief"},
    {Medicine:"Shrimp"},
    {Medicine:"Dicyclomine Hydrochloride"},
    {Medicine:"Trazodone Hydrochloride"},
    {Medicine:"Lingerie De Peau BB Beauty Booster Invisible Skin-Fusion Multi-Perfecting Makeup With Sunscreen Broad Spectrum SPF 30 LIGHT"},
    {Medicine:"CVS Daily Acne Clearing Scrub"},
    {Medicine:"Finafta"},
    {Medicine:"NATURAL SUN AQ TOTAL ANTI-AGING ESSENCE SUN"},
    {Medicine:"Baycadron"},
    {Medicine:"Hydroxyzine"},
    {Medicine:"Outback 2-in-1"},
    {Medicine:"Trazodone Hydrochloride"},
    {Medicine:"SinuClean"},
    {Medicine:"Hormodendrum"},
    {Medicine:"Oxycodone and Acetaminophen"},
    {Medicine:"Alfenta"},
    {Medicine:"Oxygen"},
    {Medicine:"Aztreonam"},
    {Medicine:"Eye Care"},
    {Medicine:"Arroyo Willow"},
    {Medicine:"Levothyroxine Sodium"},
    {Medicine:"ConRx AR"},
    {Medicine:"Omeprazole"},
    {Medicine:"Redness reliever"},
    {Medicine:"Apis venenum purum 5"},
    {Medicine:"LANEIGE BB Cushion Dark"},
    {Medicine:"First Aid Value Pack - 77 Pieces"},
    {Medicine:"Fentanyl Citrate, Bupivacaine HCl"},
    {Medicine:"Penicillium Mixture"},
    {Medicine:"Gabapentin"},
    {Medicine:"FOREVER LASTING ESSENTIAL EMULSION"},
    {Medicine:"good neighbor pharmacy Night time"},
    {Medicine:"Exforge"},
    {Medicine:"DELFLEX"},
    {Medicine:"Actonel"},
    {Medicine:"DiorSkin Nude 052 Rosy Bronze"},
    {Medicine:"Meijer"},
    {Medicine:"Oxybutynin Chloride"},
    {Medicine:"Oxygen"},
    {Medicine:"COBROXIN"},
    {Medicine:"Silver Sulfadiazene"},
    {Medicine:"Biore"},
    {Medicine:"Banana Boat Natural Reflect Sunscreen SPF 50 Plus"},
    {Medicine:"Letrozole"},
    {Medicine:"CC Daily Correct Broad Spectrum SPF 35 Sunscreen"},
    {Medicine:"Desert Beige"},
    {Medicine:"amlodipine besylate and benazepril hydrochloride"},
    {Medicine:"Sitavig"},
    {Medicine:"Glycine"},
    {Medicine:"Orange Scented Hand Sanitizer"},
    {Medicine:"Minoxidil"},
    {Medicine:"Choice OB DHA"},
    {Medicine:"Cyzone"},
    {Medicine:"Terazosin Hydrochloride"},
    {Medicine:"Esterified Estrogens and Methyltestosterone"},
    {Medicine:"smart sense 3 day treatment"},
    {Medicine:"Oxygen-Carbon Dioxide Mixture"},
    {Medicine:"Sibling Jealousy"},
    {Medicine:"Glyburide and Metformin Hydrochloride"},
    {Medicine:"Crinone"},
    {Medicine:"Simvastatin"},
    {Medicine:"Clopidogrel Bisulfate"},
    {Medicine:"Ionite APF"},
    {Medicine:"Theraprofen-90"},
    {Medicine:"Allergy Relief"},
    {Medicine:"PAROXETINE HYDROCHLORIDE"},
    {Medicine:"Diazepam"},
    {Medicine:"PROSOPIS JULIFLORA POLLEN"},
    {Medicine:"Topotecan hydrochloride"},
    {Medicine:"FENTANYL TRANSDERMAL SYSTEM"},
    {Medicine:"Glimepiride"},
    {Medicine:"Promethazine Hydrochloride"},
    {Medicine:"GUNA-Beta-ESTRADIOL"},
    {Medicine:"Valacyclovir Hydrochloride"},
    {Medicine:"CYZONE"},
    {Medicine:"albuterol sulfate"},
    {Medicine:"PRENATE DHA"},
    {Medicine:"Isopropyl alcohol"},
    {Medicine:"EXCEDRIN"},
    {Medicine:"Ursodiol"},
    {Medicine:"Dipyridamole"},
    {Medicine:"Silk"},
    {Medicine:"Naproxen"},
    {Medicine:"Gelato Topical Anesthetic"},
    {Medicine:"ENALAPRIL MALEATE"},
    {Medicine:"Torsemide"},
    {Medicine:"Methylergonovine Maleate"},
    {Medicine:"Standardized Grass Pollen, Ryegrass"},
    {Medicine:"Remedy Antifungal"},
    {Medicine:"INDOMETHACIN ER"},
    {Medicine:"LBEL Couler Luxe Supreme XP"},
    {Medicine:"Povidone Iodine"},
    {Medicine:"HYVEE"},
    {Medicine:"Solution"},
    {Medicine:"RISPERIDONE"},
    {Medicine:"Ofloxacin"},
    {Medicine:"Famotidine"},
    {Medicine:"Diclofenac Potassium"},
    {Medicine:"Good Neighbor Pharmacy Night Time"},
    {Medicine:"Tobramycin"},
    {Medicine:"Neocidin"},
    {Medicine:"Healing Waters Peach Nectarine Hand Sanitizer"},
    {Medicine:"Preferred Plus Pharmacy 3 percent Hydrogen Peroxide Wipes"},
    {Medicine:"Levothyroxine Sodium"},
    {Medicine:"Servo-Stat TE"},
    {Medicine:"Allerforce"},
    {Medicine:"Reglan"},
    {Medicine:"Hwang Geum-San Gold Hair"},
    {Medicine:"Perrigo Benzoyl Peroxide"},
    {Medicine:"Lamotrigine"},
    {Medicine:"Sotalol Hydrochloride"},
    {Medicine:"EXALGO"},
    {Medicine:"Dizziness - Vertigo"},
    {Medicine:"Childrens Allergy"},
    {Medicine:"Metformin Hydrochloride"},
    {Medicine:"Metformin Hydrochloride"},
    {Medicine:"Pollens - Trees, Eucalyptus (Blue Gum) Eucalyptus globulus"},
    {Medicine:"XOTEN-C"},
    {Medicine:"PHENTERMINE HYDROCHLORIDE"},
    {Medicine:"Meloxicam"},
    {Medicine:"pain relief pm"},
    {Medicine:"LOSARTAN POTASSIUM"},
    {Medicine:"Gastritis - Ulcer"},
    {Medicine:"benzonatate"},
    {Medicine:"Salicylic Acid"},
    {Medicine:"Linkus Lozenges"},
    {Medicine:"Doxycycline Hyclate"},
    {Medicine:"nitetime cold and flu"},
    {Medicine:"Circulatone"},
    {Medicine:"Bronchial Cough"},
    {Medicine:"Amlodipine Besylate and Benazepril Hydrochloride"},
    {Medicine:"Summer Bouquet Antibacterial Foaming Hand Wash"},
    {Medicine:"Namenda"},
    {Medicine:"Levofloxacin"},
    {Medicine:"Quinapril"},
    {Medicine:"Childrens"},
    {Medicine:"Neptune E2 ANTISEPTIC FOAM HAND"},
    {Medicine:"LOVAZA"},
    {Medicine:"Differin"},
    {Medicine:"Fungal Plus"},
    {Medicine:"The Amazing SPIDER-MAN Hand Sanitizer Moisturizing With Vitamin E and Aloe"},
    {Medicine:"Canary Grass"},
    {Medicine:"Promethazine Hydrochloride"},
    {Medicine:"Motion sickness"},
    {Medicine:"Childrens Mucinex"},
    {Medicine:"Antiseptic Mouth Rinse"},
    {Medicine:"Antibacterial"},
    {Medicine:"PHOENIX HEALTHCARE SOLUTIONS, LLC"},
    {Medicine:"Amoxicillin and Clavulanate Potassium"},
    {Medicine:"good neighbor pharmacy complete"},
    {Medicine:"chlorpromazine hydrochloride"},
    {Medicine:"Ramipril"},
    {Medicine:"HUA TUO XIAN GAO"},
    {Medicine:"Red Pepper"},
    {Medicine:"Diazepam"},
    {Medicine:"simvastatin"},
    {Medicine:"Runny Nose Warts"},
    {Medicine:"SIMPLY RIGHT BODY CARE"},
    {Medicine:"Glipizide"},
    {Medicine:"Glyburide and Metformin Hydrochloride"},
    {Medicine:"Velvet Grass Pollen"},
    {Medicine:"Verapamil Hydrochloride"},
    {Medicine:"Pain ReliefRoll On"},
    {Medicine:"Ramipril"},
    {Medicine:"Kogenate FS"},
    {Medicine:"PredniSONE"},
    {Medicine:"DYNACIN"},
    {Medicine:"HYDROCODONE BITARTRATE AND ACETAMINOPHEN"},
    {Medicine:"Syeda"},
    {Medicine:"Furosemide"},
    {Medicine:"gemcitabine"},
    {Medicine:"Pioglitazone and metformin"},
    {Medicine:"WAL-DRYL ALLERGY"},
    {Medicine:"Shopko Camphor Phenol Gel"},
    {Medicine:"Cucumber Melon Scented Hand Sanitizer"},
    {Medicine:"Witch Hazel"},
    {Medicine:"Gas Relief"},
    {Medicine:"Quinidine Gluconate"},
    {Medicine:"Aurum Plumbum"},
    {Medicine:"Ailanthus"},
    {Medicine:"WhiskCare 373"},
    {Medicine:"Treatment Set TS332850"},
    {Medicine:"tussin dm"},
    {Medicine:"Denorex Therapeutic"},
    {Medicine:"Orajel Instant Relief for Teething Pain"},
    {Medicine:"STOOL SOFTENER GENTLE RELIEF"},
    {Medicine:"FINASTERIDE"},
    {Medicine:"Clarinex"},
    {Medicine:"Pepbis"},
    {Medicine:"Deb Gold"},
    {Medicine:"lisinopril"},
    {Medicine:"Risperidone"},
    {Medicine:"Daily Moisturizing"},
    {Medicine:"Hydrochlorothiazide"},
    {Medicine:"Sodium Thiosulfate"},
    {Medicine:"COREG"},
    {Medicine:"METHOTREXATE SODIUM"},
    {Medicine:"Spironolactone"},
    {Medicine:"Shopko Antibacterial Foaming Hand Sanitizer"},
    {Medicine:"FIRMING DAY"},
    {Medicine:"Kinerase"},
    {Medicine:"Oralair"},
    {Medicine:"Metoprolol Tartrate"},
    {Medicine:"Secura Moisturizing Cleanser"},
    {Medicine:"Quietude"},
    {Medicine:"Lymph Detox"},
    {Medicine:"LEADER HYDROCORTISONE WITH ALOE"},
    {Medicine:"Lamotrigine"},
    {Medicine:"3 Step First Aid Kit"},
    {Medicine:"Dr G Whitening REFORMER by EGF"},
    {Medicine:"Isopropyl Alcohol Surgical Scrub"},
    {Medicine:"Ceftriaxone"},
    {Medicine:"Chlorzoxazone"},
    {Medicine:"3M Nexcare Cold Sore Treatment"},
    {Medicine:"Glytone Acne Facial Masque"},
    {Medicine:"Nifedipine"},
    {Medicine:"nite time"},
    {Medicine:"Enalapril Maleate"},
    {Medicine:"XANTHIUM STRUMARIUM VAR CANADENSE POLLEN"},
    {Medicine:"Cortizone 10 Intensive Healing for Eczema"},
    {Medicine:"CASUARINA EQUISETIFOLIA POLLEN"},
    {Medicine:"Stool Softener"},
    {Medicine:"Levoxyl"},
    {Medicine:"Foamy Med-I-San"},
    {Medicine:"Tork Premium Hand Sanitizer Foam Alcohol-Free"},
    {Medicine:"Good Neighbor Pharmacy Vitamin A and D"},
    {Medicine:"NAFCILLIN SODIUM"},
    {Medicine:"Spironolactone and Hydrochlorothiazide"},
    {Medicine:"Extra Strength QPAP"},
    {Medicine:"Stridex"},
    {Medicine:"Gold Bond Foot"},
    {Medicine:"Dove"},
    {Medicine:"ARNICA MONTANA (WHOLE PLANT)"},
    {Medicine:"Prempro"},
    {Medicine:"Fulton Street Market Omeprazole"},
    {Medicine:"SERTRALINE HYDROCHLORIDE"},
    {Medicine:"Pristiq"},
    {Medicine:"Dicloxacillin Sodium"},
    {Medicine:"Venlafaxine Hydrochloride"},
    {Medicine:"Nicotine"},
    {Medicine:"Sulfacetamide Sodium"},
    {Medicine:"Collagen"},
    {Medicine:"Escitalopram"},
    {Medicine:"Lorazepam"},
    {Medicine:"Forever Young Hand Broad Spectrum SPF 40"},
    {Medicine:"Lorazepam"},
    {Medicine:"Duloxetine"},
    {Medicine:"Clozapine"},
    {Medicine:"Pussy Willow"},
    {Medicine:"Sulwhasoo Snowise Foundation"},
    {Medicine:"Glycopyrrolate"},
    {Medicine:"Trazodone Hydrochloride"},
    {Medicine:"Banophen"},
    {Medicine:"Crest 3D White"},
    {Medicine:"Methocarbamol"},
    {Medicine:"Opahl"},
    {Medicine:"PredniSONE"},
    {Medicine:"NARS Pure Radiant Tinted Moisturizer"},
    {Medicine:"TONYMOLY INTENSE CARE GOLD 24K SNAIL"},
    {Medicine:"Equate Cool and Heat"},
    {Medicine:"PROCURE VITAMIN A AND D"},
    {Medicine:"Cattle Epithelium"},
    {Medicine:"Lisinopril and Hydrochlorothiazide"},
    {Medicine:"Promethazine Hydrochloride"},
    {Medicine:"Oral Saline Laxative"},
    {Medicine:"ESSENTIAL SOLUTION VITA C MASK SHEET"},
    {Medicine:"Azathioprine"},
    {Medicine:"Pollens - Trees, Cottonwood, Common Populus deltoides"},
    {Medicine:"Ivory Always color stay-on Makeup Broad Spectrum SPF 15"},
    {Medicine:"Cepacol Sensations"},
    {Medicine:"LISINOPRIL AND HYDROCHLOROTHIAZIDE"},
    {Medicine:"Nigrospora sphaerica"},
    {Medicine:"Bubble Gum Sunscreen Lip Moisturizer"},
    {Medicine:"Cold and Flu Nighttime"},
    {Medicine:"Mineral Oil"},
    {Medicine:"Nasal Decongestant"},
    {Medicine:"KALI PHOSPHORICUM"},
    {Medicine:"PILOCARPINE HYDROCHLORIDE"},
    {Medicine:"Glyburide and Metformin Hydrochloride"},
    {Medicine:"CD DIORSKIN NUDE CREME Nude Glow Creme Gel Compact Makeup Sunscreen Broad Spectrum SPF20 040"},
    {Medicine:"Stat-Foam"},
    {Medicine:"CALCAREA SULPHURICA"},
    {Medicine:"Depakote"},
    {Medicine:"Fluconazole"},
    {Medicine:"Hansan Spray"},
    {Medicine:"BETAXOLOL HYDROCHLORIDE"},
    {Medicine:"RoC Multi Correxion"},
    {Medicine:"Lorac Foundation Fair"},
    {Medicine:"Adult Tussin DM Max"},
    {Medicine:"Molds, Rusts and Smuts, Epicoccum nigrum"},
    {Medicine:"Promethazine Hydrochloride"},
    {Medicine:"The Natural Dentist"},
    {Medicine:"Cortizone 10 Intensive Healing"},
    {Medicine:"Mouth Rinse"},
    {Medicine:"Body"},
    {Medicine:"Zodryl AC 40"},
    {Medicine:"PROMETHAZINE HYDROCHLORIDE"},
    {Medicine:"Diphenoxylate Hydrochloride and Atropine Sulfate"},
    {Medicine:"CLARINS Broad Spectrum SPF 15 Everlasting Foundation Tint 108"},
    {Medicine:"Childrens Allergy"},
    {Medicine:"Blistex"},
    {Medicine:"Leader Ibuprofen"},
    {Medicine:"DROSPIRENONE AND ETHINYL ESTRADIOL"},
    {Medicine:"DIPYRIDAMOLE"},
    {Medicine:"Olanzapine and Fluoxetine"},
    {Medicine:"Ergomar"},
    {Medicine:"Nioxin Scalp Recovery"},
    {Medicine:"Finasteride"},
    {Medicine:"Cashew"},
    {Medicine:"Diphenhydramine"},
    {Medicine:"AMOXICILLIN"},
    {Medicine:"Superdent"},
    {Medicine:"Alfalco"},
    {Medicine:"flawless by Sonya aloe BB creme COCOA SPF 10 Sunscreen"},
    {Medicine:"ADVIL PM"},
    {Medicine:"Doxycycline Monohydrate"},
    {Medicine:"FUSARIUM VASINFECTUM OXYSPORUM"},
    {Medicine:"Tinidazole"},
    {Medicine:"Walgreens SunscreenSPF 70"},
    {Medicine:"Minocycline Hydrochloride"},
    {Medicine:"Pepper Tree Pollen"},
    {Medicine:"Healthy Accents triple antibiotic"},
    {Medicine:"Firebush/Burning Bush"},
    {Medicine:"RISPERIDONE"},
    {Medicine:"Tretinoin"},
    {Medicine:"JiDeSheng"},
    {Medicine:"HEADACHE HP"},
    {Medicine:"CY BETTER LIPS BALM Humectante para Labios con color FPS 18"},
    {Medicine:"Anxiolix"},
    {Medicine:"Sodium Sulfacetamide 10 Sulfur 5 Cleanser"},
    {Medicine:"Novolin"},
    {Medicine:"MethylPREDNISolone"},
    {Medicine:"CAFFEINE CITRATE"},
    {Medicine:"Synthroid"},
    {Medicine:"Nalbuphine Hydrochloride"},
    {Medicine:"Zolpidem Tartrate"},
    {Medicine:"Blistex"},
    {Medicine:"Kimvent Oral Care Suction Swab pack"},
    {Medicine:"Minocin"},
    {Medicine:"CLADOSPORIUM SPHAEROSPERMUM"},
    {Medicine:"PRO-LONGWEAR"},
    {Medicine:"Instant Hand Sanitizer Strawberry Kiss"},
    {Medicine:"AllergyEase Pacific"},
    {Medicine:"JUGLANS REGIA POLLEN"},
    {Medicine:"tizanidine hydrochloride"},
    {Medicine:"ENALAPRIL MALEATE"},
    {Medicine:"Pharbedryl"},
    {Medicine:"Concept OB"},
    {Medicine:"Tigan"},
    {Medicine:"SUN Tinted Solar Defense Organic SPF 30"},
    {Medicine:"Quinapril"},
    {Medicine:"Cetirizine Hydrochloride"},
    {Medicine:"Captopril"},
    {Medicine:"Topcare Milk of Magnesia"},
    {Medicine:"Simvastatin"},
    {Medicine:"La Prairie Switzerland"},
    {Medicine:"Metoprolol Succinate"},
    {Medicine:"Risperidone"},
    {Medicine:"Glycopyrrolate"},
    {Medicine:"Acetaminophen"},
    {Medicine:"Bryophyllum Argentum"},
    {Medicine:"Bellagio Sunscreen SPF 30"},
    {Medicine:"Colgate"},
    {Medicine:"Citrus Hand Sanitizer with vitamin E and aloe"},
    {Medicine:"Fluoxetine"},
    {Medicine:"Lidocaine Hydrochloride"},
    {Medicine:"Hawaiian Tropic Tanning"},
    {Medicine:"Cefadroxil"},
    {Medicine:"Old Spice Red Zone Sweat Defense"},
    {Medicine:"RIVASTIGMINE TARTRATE"},
    {Medicine:"VICTRELIS"},
    {Medicine:"DELTUSS DMX Cough Suppressant Nasal Decongestant Antihistamine GRAPE Flavor"},
    {Medicine:"Topiramate"},
    {Medicine:"MUSCLE CRAMPS"},
    {Medicine:"Losartan Potassium"},
    {Medicine:"Flecainide Acetate"},
    {Medicine:"Divalproex Sodium Delayed Release"},
    {Medicine:"MICONAZOLE"},
    {Medicine:"Loperamide Hydrochloride"},
    {Medicine:"Western Sycamore Pollen"},
    {Medicine:"Pulmo Tartarus 6/8"},
    {Medicine:"Paroxetine"},
    {Medicine:"Amoxicillin and Clavulanate Potassium"},
    {Medicine:"quetiapine fumarate"},
    {Medicine:"Amoxicillin"},
    {Medicine:"DR SMITHS DIAPER"},
    {Medicine:"Beauty Without Cruelty - Broad Spectrum SPF 18"},
    {Medicine:"OrthoWash"},
    {Medicine:"Nimodipine"},
    {Medicine:"XtraCare Skin Relief Oatmeal Daily Moisturizing"},
    {Medicine:"Suave"},
    {Medicine:"Theraflu"},
    {Medicine:"Muscle and Joint"},
    {Medicine:"Viscum Populi"},
    {Medicine:"Dexbrompherniramine Maleate and Pseudoephedrine Sulfate"},
    {Medicine:"Clonidine Hydrochloride"},
    {Medicine:"Arnica Plus"},
    {Medicine:"Veneno de Abeja"},
    {Medicine:"Myrbetriq"},
    {Medicine:"Acetaminophen-APAP 8 Hour"},
    {Medicine:"smart sense sinus"},
    {Medicine:"Goodys Headache Relief Shot"},
    {Medicine:"LidoCream 4"},
    {Medicine:"Enablex"},
    {Medicine:"Dukal Alcohol Prep Pad"},
    {Medicine:"Azelastine Hydrochloride"},
    {Medicine:"Cenestin"},
    {Medicine:"Treatment Set TS333743"},
    {Medicine:"Meijer Sport SPF 50"},
    {Medicine:"ECOZA"},
    {Medicine:"Cetirizine Hydrochloride"},
    {Medicine:"Night time sinus"},
    {Medicine:"Fentanyl Citrate, Bupivacaine HCl"},
    {Medicine:"ANTIBACTERIAL FOAMING"},
    {Medicine:"All Day Allergy"},
    {Medicine:"nasal decongestant"},
    {Medicine:"Pravastatin Sodium"},
    {Medicine:"THROMBIN-JMI"},
    {Medicine:"Ondansetron"},
    {Medicine:"Sulfamethoxazole and Trimethoprim"},
    {Medicine:"ZzzQuil"},
    {Medicine:"Perrigo Seb Prev"},
    {Medicine:"smart sense acid reducer"},
    {Medicine:"Terbutaline Sulfate"},
    {Medicine:"Lotrel"},
    {Medicine:"rx act pain relief"},
    {Medicine:"NoHist LQ"},
    {Medicine:"Secret Antiperspirant"},
    {Medicine:"PSORIASIS"},
    {Medicine:"Azithromycin"},
    {Medicine:"Care One Pain Relief"},
    {Medicine:"Calcium carbonate"},
    {Medicine:"Enalapril Maleate"},
    {Medicine:"Warfarin Sodium"},
    {Medicine:"Colitis"},
    {Medicine:"Estradiol"},
    {Medicine:"Anastrozole"},
    {Medicine:"Cuprimine"},
    {Medicine:"LBEL Couleur Luxe Rouge Amplifier XP amplifying SPF 15"},
    {Medicine:"Dermal Wound Cleanser"},
    {Medicine:"Gabapentin"},
    {Medicine:"Olanzapine"},
    {Medicine:"Cymbalta"},
    {Medicine:"healthy accents nighttime cold and flu"},
    {Medicine:"Neutrogena Nourishing Eye Quad"},
    {Medicine:"IMITREX"},
    {Medicine:"NU-DERM Tolereen"},
    {Medicine:"Oily Hair Dandruff"},
    {Medicine:"LOreal Paris Advanced Suncare Invisible Protect Dry 30 Broad Spectrum SPF 30 Sunscreen"},
    {Medicine:"Albuterol"},
    {Medicine:"Cold Multi-Symptom Daytime Non-Drowsy"},
    {Medicine:"EXCEDRIN"},
    {Medicine:"Bactoshield CHG"},
    {Medicine:"Ranitidine"},
    {Medicine:"IL-10"},
    {Medicine:"Nafcillin Sodium"},
    {Medicine:"Diazepam"},
    {Medicine:"Neutrogena Healthy Defense Daily Moisturizer"},
    {Medicine:"Atenolol and Chlorthalidone"},
    {Medicine:"Air"},
    {Medicine:"Amoxicillin and Clavulanate Potassium"},
    {Medicine:"Acetaminophen"},
    {Medicine:"Hydrogen Peroxide"},
    {Medicine:"OPANA"},
    {Medicine:"Naturasil"},
    {Medicine:"Salonpas pain relieving GEL-PATCH HOT"},
    {Medicine:"Metformin Hydrochloride"},
    {Medicine:"Ondansetron"},
    {Medicine:"ARIXTRA"},
    {Medicine:"Gelato Topical Anesthetic"},
    {Medicine:"MARVEL ULTIMATE SPIDER-MAN ANTISEPTIC HAND CLEANSING BERRY SCENTED"},
    {Medicine:"Cetirizine Hydrochloride"},
    {Medicine:"Faith Family Ducks Antiseptic Hand Cleansing"},
    {Medicine:"Propranolol Hydrochloride"},
    {Medicine:"Beyond Color"},
    {Medicine:"Apis Regina Cerebri"},
    {Medicine:"Ranitidine"},
    {Medicine:"Pollens - Trees, Boxelder/Maple Mix"},
    {Medicine:"Vida Mia Hand Sanitizer Aloe Vera"},
    {Medicine:"Hydralazine Hydrochloride"},
    {Medicine:"Ranitidine"},
    {Medicine:"Clean and Clear Advantage"},
    {Medicine:"Balsam Poplar"},
    {Medicine:"Gliadel"},
    {Medicine:"Donepezil hydrochloride"},
    {Medicine:"KROGER"},
    {Medicine:"Vigofem Plus for Women"},
    {Medicine:"Sun Shades Lip Balm"},
    {Medicine:"good neighbor pharmacy nicotine"},
    {Medicine:"Good Neighbor Pharmacy Sleep Aid"},
    {Medicine:"Kleen Instant Hand Sanitizer with Moisturizers"},
    {Medicine:"fabulous face"},
    {Medicine:"Carbamazepine"},
    {Medicine:"Nifedipine"},
    {Medicine:"Neutral Sodium Fluoride"},
    {Medicine:"Original Extra Strong All Natural Fishermans Friend Menthol Cough Suppressant"},
    {Medicine:"Anti-Bacterial Hand"},
    {Medicine:"FUROSEMIDE"},
    {Medicine:"Sweet Gum"},
    {Medicine:"Antibacterial Hand"},
    {Medicine:"risperidone"},
    {Medicine:"Sulfamethoxazole and Trimethoprim"},
    {Medicine:"Trihexyphenidyl Hydrochloride"},
    {Medicine:"AllergyEase Egg and Meat"},
    {Medicine:"SKIN 79 Super Plus Beblesh Balm Triple Functions SPF25 PA (40g)"},
    {Medicine:"Isomers Clear Skin Acne Treatment Lotion"},
    {Medicine:"Diurex"},
    {Medicine:"meloxicam"},
    {Medicine:"Oxaliplatin"},
    {Medicine:"Tirosint"},
    {Medicine:"Ramipril"},
    {Medicine:"Acid Reducer"},
    {Medicine:"Ferrum sidereum Pancreas 10/4 Special Order"},
    {Medicine:"Citalopram"},
    {Medicine:"FENTANYL"},
    {Medicine:"Neosporin Original"},
    {Medicine:"AcneFree Sensitive"},
    {Medicine:"Daily Facial Moisturizer Broad Spectrum SPF15 Sunscreen"},
    {Medicine:"pain reliever"},
    {Medicine:"Cyclosporine"},
    {Medicine:"English Walnut"},
    {Medicine:"Anti-Aging Hydra Tint SPF 20 Shade 30"},
    {Medicine:"Childrens Mucinex"},
    {Medicine:"Sally Hansen Ouch-Relief"},
    {Medicine:"SPF 50 UVA/UVB"},
    {Medicine:"Nitrogen"},
    {Medicine:"Quinapril Hydrochloride and Hydrochlorothiazide"},
    {Medicine:"Phentermine Hydrochloride"},
    {Medicine:"Lorazepam"},
    {Medicine:"Caverject Impulse"},
    {Medicine:"Coffea Cruda Kit Refill"},
    {Medicine:"allergy"},
    {Medicine:"Timoptic"},
    {Medicine:"Smart San Alcohol Free Hand Sanitizer Foam"},
    {Medicine:"Trichophyton Mixture"},
    {Medicine:"PROCRIT"},
    {Medicine:"Scot-Tussin Expectorant SF Cough"},
    {Medicine:"Miracle Heel Repair"},
    {Medicine:"Ampicillin and Sulbactam"},
    {Medicine:"McKesson Alcohol Prep Pad"},
    {Medicine:"Clobetasol Propionate"},
    {Medicine:"ALLEGRA"},
    {Medicine:"Risperidone"},
    {Medicine:"Morphine Sulfate"},
    {Medicine:"Healthy Accents Antibacterial Body Wash"},
    {Medicine:"Meijer Oil Free SPF 30"},
    {Medicine:"STRATTERA"},
    {Medicine:"Junior Pain Relief"},
    {Medicine:"Robinul"},
    {Medicine:"Isolyte S pH 7.4"},
    {Medicine:"Menstrual Headache"},
    {Medicine:"Fungicure"},
    {Medicine:"ELIGARD"},
    {Medicine:"Cilostazol"},
    {Medicine:"Cephalexin"},
    {Medicine:"Levothyroxine Sodium"},
    {Medicine:"good sense pain relief"},
    {Medicine:"Lidocaine Hydrochloride"},
    {Medicine:"Hydralazine Hydrochloride"},
    {Medicine:"ESIKA Silk Skin SPF 9"},
    {Medicine:"Annual Blue Grass"},
    {Medicine:"nitrogen"},
    {Medicine:"PERIOSCIENCES White Care AO Pro"},
    {Medicine:"Nitrofurantoin (macrocrystals)"},
    {Medicine:"Meclizine Hydrochloride"},
    {Medicine:"EXTRA"},
    {Medicine:"Sun Essential"},
    {Medicine:"Creations Garden"},
    {Medicine:"PVP Prep"},
    {Medicine:"LIP CONDITIONER"},
    {Medicine:"AGAVE TEQUILANA"},
    {Medicine:"Citalopram"},
    {Medicine:"OP Protective Spray Gel 8"},
    {Medicine:"expectorant cough"},
    {Medicine:"PURELL Advanced Green Certified Instant Hand Sanitizer"},
    {Medicine:"Tranexamic Acid"},
    {Medicine:"Rasuvo"},
    {Medicine:"METOPROLOL SUCCINATE"},
    {Medicine:"FOSINOPRIL SODIUM"},
    {Medicine:"Antiseptic"},
    {Medicine:"Laxative Pills"},
    {Medicine:"Trihexyphenidyl Hydrochloride"},
    {Medicine:"Cold Remedy"},
    {Medicine:"Cilostazol"},
    {Medicine:"DOVE"},
    {Medicine:"Vandetanib"},
    {Medicine:"Epiphysis Plumbum"},
    {Medicine:"SOLENOPSIS INVICTA"},
    {Medicine:"Exelon"},
    {Medicine:"LBEL"},
    {Medicine:"Imipramine Hydrochloride"},
    {Medicine:"Norpramin"},
    {Medicine:"nicotine"},
    {Medicine:"Amitriptyline Hydrochloride"},
    {Medicine:"Aspirin"},
    {Medicine:"Stavudine"},
    {Medicine:"Instant Hand Sanitizer"},
    {Medicine:"Everyday Clean Dandruff"},
    {Medicine:"DIVALPROEX SODIUM"},
    {Medicine:"SHISEIDO PERFECT REFINING FOUNDATION"},
    {Medicine:"Oxacillin"},
    {Medicine:"Adult Low Dose Aspirin"},
    {Medicine:"Methocarbamol"},
    {Medicine:"Natralia Cramp Relief"},
    {Medicine:"Clarithromycin"},
    {Medicine:"Head and Shoulders"},
    {Medicine:"Colgate Anticavity"},
    {Medicine:"CD DIORSNOW UV SHIELD BB CREME LIGHT SHADE WHITE REVEAL UV PROTECTION SPF 50"},
    {Medicine:"Hydrocodone Bitartate and Acetaminophen"},
    {Medicine:"Temazepam"},
    {Medicine:"Fluvastatin"},
    {Medicine:"Perphenazine and Amitriptyline Hydrochloride"},
    {Medicine:"Fenofibrate"},
    {Medicine:"NAPROXEN"},
    {Medicine:"BURBERRY FRESH GLOW B.B. LUMINOUS SKIN PERFECTING BEAUTY BALM SUNSCREEN BROAD SPECTRUM SPF 20 DARK 03"},
    {Medicine:"Mucor racemosus"},
    {Medicine:"AcneFree Severe Antibacterial Cleansing Wash"},
    {Medicine:"Gabapentin"},
    {Medicine:"Tramadol ER"},
    {Medicine:"Born Hair"},
    {Medicine:"Gyno Complex"},
    {Medicine:"Hydrocodone Bitatrate and Acetaminophen"},
    {Medicine:"All Day Pain Relief"},
    {Medicine:"Cocklebur"},
    {Medicine:"Hasol Anti hair loss day tonic"},
    {Medicine:"Ondansetron"},
    {Medicine:"Eszopiclone"},
    {Medicine:"AMOXICILLIN"},
    {Medicine:"BUDEPRION"},
    {Medicine:"Australian Gold"},
    {Medicine:"Methylprednisolone"},
    {Medicine:"Valproic Acid"},
    {Medicine:"Nitrofurantoin"},
    {Medicine:"True Beige"},
    {Medicine:"LIOTHYRONINE SODIUM"},
    {Medicine:"Nitrous Oxide"},
    {Medicine:"Dry Cough Diarrhea"},
    {Medicine:"Bilboa Capri Sunscreen SPF 30"},
    {Medicine:"Body Luxuries Dahlia Blossom Scented Waterless Anti Bacterial Hand gel"},
    {Medicine:"VANICREAM"},
    {Medicine:"DiBromm"},
    {Medicine:"good sense athletes foot"},
    {Medicine:"Envirotox"},
    {Medicine:"Deb Med Antimicrobial Foaming Hand Wash Fragrance Free Dye Free"},
    {Medicine:"Sleep RELIEF"},
    {Medicine:"Doxycycline"},
    {Medicine:"Tramadol Hydrochloride"},
    {Medicine:"Fentanyl Citrate"},
    {Medicine:"TOPIRAMATE"},
    {Medicine:"Phenylephrine Hydrochloride"},
    {Medicine:"Meloxicam"},
    {Medicine:"ROBAXIN"},
    {Medicine:"Mederma PM"},
    {Medicine:"Sage"},
    {Medicine:"All Day Relief"},
    {Medicine:"Magnesium Sulfate"},
    {Medicine:"Sleep Aid"},
    {Medicine:"Arnuity Ellipta"},
    {Medicine:"Imodium"},
    {Medicine:"Bisacodyl"},
    {Medicine:"PediaCare Childrens Plus Cough and Runny Nose"},
    {Medicine:"LA MER THE TREATMENT FLUID FOUNDATION"}]


export const MedicalStores=[
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
    },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
    {
        ShopName:"Nellore Medicals",
        OwnerName:"Venu",
        Address:{
            D_No:"5/96",
            Street:"Ysr Nagar",
            Area:"Buja Buja Nellore",
            City:"Nellore",
            District:"Nellore",
            State:"Andhra Pradesh",
            Country:"India",
            PinCode:"589641"
        },
        Distance:"7",
        Ratting:"3.5",
        Status:"Opened",
        Number:"9876543210",
        Timings:"9am-9pm",
        Offers:{
            one:"Flat 20% off on All Medicines",
            two:"Flat 5% off on Skin care Products",
            three:"Flat 10% off on Dabur Brand Products"
        },
        Images:{
            Ione:medstore1,
            Itwo:medstore2
        }
    },
]

export const Doctors=[
    {
        DoctorPhoto:Doctor,
        Name: 'Dr.Srinivasulu',
        Education:"Mbbs",
        Role:"Surgeon",
        Experience:"10+Years",
        Hospital:"Apollo",
        Ratting:"4.5",
        Achievements:{
            one:"Done 3000+ Operations in 10 years",
            two:"Treated Many Officials Including Movie Stars",
            three:"Awarded by AIIMS for Treating Most Critical Cases",
        }
    },
    {
        DoctorPhoto:Doctor,
        Name: 'Dr.Srinivasulu',
        Education:"Mbbs",
        Role:"Surgeon",
        Experience:"10+Years",
        Hospital:"Apollo",
        Ratting:"4.5",
        Achievements:{
            one:"Done 3000+ Operations in 10 years",
            two:"Treated Many Officials Including Movie Stars",
            three:"Awarded by AIIMS for Treating Most Critical Cases",
        }
    },
    {
        DoctorPhoto:Doctor,
        Name: 'Dr.Srinivasulu',
        Education:"Mbbs",
        Role:"Surgeon",
        Experience:"10+Years",
        Hospital:"Apollo",
        Ratting:"4.5",
        Achievements:{
            one:"Done 3000+ Operations in 10 years",
            two:"Treated Many Officials Including Movie Stars",
            three:"Awarded by AIIMS for Treating Most Critical Cases",
        }
    },
    {
        DoctorPhoto:Doctor,
        Name: 'Dr.Srinivasulu',
        Education:"Mbbs",
        Role:"Surgeon",
        Experience:"10+Years",
        Hospital:"Apollo",
        Ratting:"4.5",
        Achievements:{
            one:"Done 3000+ Operations in 10 years",
            two:"Treated Many Officials Including Movie Stars",
            three:"Awarded by AIIMS for Treating Most Critical Cases",
        }
    },
    {
        DoctorPhoto:Doctor,
        Name: 'Dr.Srinivasulu',
        Education:"Mbbs",
        Role:"Surgeon",
        Experience:"10+Years",
        Hospital:"Apollo",
        Ratting:"4.5",
        Achievements:{
            one:"Done 3000+ Operations in 10 years",
            two:"Treated Many Officials Including Movie Stars",
            three:"Awarded by AIIMS for Treating Most Critical Cases",
        }
    },
    {
        DoctorPhoto:Doctor,
        Name: 'Dr.Srinivasulu',
        Education:"Mbbs",
        Role:"Surgeon",
        Experience:"10+Years",
        Hospital:"Apollo",
        Ratting:"4.5",
        Achievements:{
            one:"Done 3000+ Operations in 10 years",
            two:"Treated Many Officials Including Movie Stars",
            three:"Awarded by AIIMS for Treating Most Critical Cases",
        }
    },
    {
        DoctorPhoto:Doctor,
        Name: 'Dr.Srinivasulu',
        Education:"Mbbs",
        Role:"Surgeon",
        Experience:"10+Years",
        Hospital:"Apollo",
        Ratting:"4.5",
        Achievements:{
            one:"Done 3000+ Operations in 10 years",
            two:"Treated Many Officials Including Movie Stars",
            three:"Awarded by AIIMS for Treating Most Critical Cases",
        }
    },
    {
        DoctorPhoto:Doctor,
        Name: 'Dr.Srinivasulu',
        Education:"Mbbs",
        Role:"Surgeon",
        Experience:"10+Years",
        Hospital:"Apollo",
        Ratting:"4.5",
        Achievements:{
            one:"Done 3000+ Operations in 10 years",
            two:"Treated Many Officials Including Movie Stars",
            three:"Awarded by AIIMS for Treating Most Critical Cases",
        }
    },
    {
        DoctorPhoto:Doctor,
        Name: 'Dr.Srinivasulu',
        Education:"Mbbs",
        Role:"Surgeon",
        Experience:"10+Years",
        Hospital:"Apollo",
        Ratting:"4.5",
        Achievements:{
            one:"Done 3000+ Operations in 10 years",
            two:"Treated Many Officials Including Movie Stars",
            three:"Awarded by AIIMS for Treating Most Critical Cases",
        }
    },
    {
        DoctorPhoto:Doctor,
        Name: 'Dr.Srinivasulu',
        Education:"Mbbs",
        Role:"Surgeon",
        Experience:"10+Years",
        Hospital:"Apollo",
        Ratting:"4.5",
        Achievements:{
            one:"Done 3000+ Operations in 10 years",
            two:"Treated Many Officials Including Movie Stars",
            three:"Awarded by AIIMS for Treating Most Critical Cases",
        }
    }
    
]

export const LabsList=[
    {
        LabImage:medstore1,
        LabName:"Lakshmi Diagnostic Center",
        LabRatting:"3.5",
        LabAddress:{
            Area:"Chinna Bazar",
            City:"Nellore"
        },
        LabDistance:"7Km",
        LabServices:["Blood Test","Sugar Test","BP Check","Health Check Up"],
        LabStatus:"Opened",
    },
    {
        LabImage:medstore1,
        LabName:"Lakshmi Diagnostic Center",
        LabRatting:"3.5",
        LabAddress:{
            Area:"Chinna Bazar",
            City:"Nellore"
        },
        LabDistance:"7Km",
        LabServices:["Blood Test","Sugar Test","BP Check","Health Check Up"],
        LabStatus:"Opened",
    },
    {
        LabImage:medstore1,
        LabName:"Lakshmi Diagnostic Center",
        LabRatting:"3.5",
        LabAddress:{
            Area:"Chinna Bazar",
            City:"Nellore"
        },
        LabDistance:"7Km",
        LabServices:["Blood Test","Sugar Test","BP Check","Health Check Up"],
        LabStatus:"Opened",
    },
    {
        LabImage:medstore1,
        LabName:"Lakshmi Diagnostic Center",
        LabRatting:"3.5",
        LabAddress:{
            Area:"Chinna Bazar",
            City:"Nellore"
        },
        LabDistance:"7Km",
        LabServices:["Blood Test","Sugar Test","BP Check","Health Check Up"],
        LabStatus:"Opened",
    },
    {
        LabImage:medstore1,
        LabName:"Lakshmi Diagnostic Center",
        LabRatting:"3.5",
        LabAddress:{
            Area:"Chinna Bazar",
            City:"Nellore"
        },
        LabDistance:"7Km",
        LabServices:["Blood Test","Sugar Test","BP Check","Health Check Up"],
        LabStatus:"Opened",
    },
    {
        LabImage:medstore1,
        LabName:"Lakshmi Diagnostic Center",
        LabRatting:"3.5",
        LabAddress:{
            Area:"Chinna Bazar",
            City:"Nellore"
        },
        LabDistance:"7Km",
        LabServices:["Blood Test","Sugar Test","BP Check","Health Check Up"],
        LabStatus:"Opened",
    },
]

export const BloodDonor=[
    {
        DonorImage:medstore3,
        DonorName:"Srinivasa Blood Bank",
        BloodGroup:"O+",
        Address:{
            Area:"Gandhi Nagar",
            City:"Nellore"
        },
        DonorContact:"9876543210",
    }
]